### ISSUE TITLE
TableFilter trying to remove null listeners

### ISSUE THREAD

**Issue by JonathanGiles** [controlsfx/controlsfx#1087]
**[Original report](https://bitbucket.org/controlsfx/controlsfx/issue/896) by Thomas Nield (Bitbucket: [thomasnield](https://bitbucket.org/thomasnield), GitHub: [thomasnield](https://github.com/thomasnield)).**

----------------------------------------

In one of my more complicated applications, the TableFilter is throwing an error. 

```
		java.lang.NullPointerException
			at com.sun.javafx.binding.ExpressionHelper.removeListener(ExpressionHelper.java:74)
			at javafx.beans.property.ObjectPropertyBase.removeListener(ObjectPropertyBase.java:92)
			at org.nield.dirtyfx.beans.DirtyObjectProperty.removeListener(DirtyObjectProperty.kt)
			at impl.org.controlsfx.table.ColumnFilter.removeBackingItem(ColumnFilter.java:243)
			at impl.org.controlsfx.table.ColumnFilter.lambda$null$2(ColumnFilter.java:74)
....
```

Digging deeper into this, here is the site of the cause:

```java
    private final HashMap<CellIdentity<T>,ChangeListener<R>> trackedCells = new HashMap<>();

... 

    private void removeBackingItem(T item, ObservableValue<R> cellValue) {
        if (cellValue == null) {
            return;
        }
        removeValue(cellValue.getValue());

        //remove listener from cell
        ChangeListener<R> listener = trackedCells.get(new CellIdentity<>(item));
        cellValue.removeListener(listener); // NullPointerException cause
        trackedCells.remove(new CellIdentity<>(item));
    }
```

I could simply just do a null-check on the listener before removing the listener, but I'm concerned there is a deeper issue going on where the `trackedCells` is missing a listener. 

The only two private methods using `trackedCells` are `addBackingItem()` and `removeBackingItem()`. 

I kind of wonder if the `WeakChangeListener` is causing this issue somehow. Any thoughts? 

```java
    private void addBackingItem(T item, ObservableValue<R> cellValue) {
        if (cellValue == null) {
            return;
        }
        if (filterValuesDupeCounter.add(cellValue.getValue()) == 1) {
            filterValues.add(new FilterValue<>(cellValue.getValue(),this));
        }

        //listen to cell value and track it
        CellIdentity<T> trackedCellValue = new CellIdentity<>(item);

		ChangeListener<R> cellListener = new WeakChangeListener(changeListener);
        cellValue.addListener(cellListener);
        trackedCells.put(trackedCellValue,cellListener);
    }
```

**Comment by thomasnield** [comment]
I am contemplating just doing a null check before removing the listener. Does anybody see any major issues in doing this?
