### ISSUE TITLE
NotificationPopupHandler.getScreenBounds throwing NPE on 11.0.0

### ISSUE THREAD

**Issue by nicolabeghin** [controlsfx/controlsfx#1140]
Hi everyone
I just updated to ControlsFX 11.0.0 (from the RC2) and I'm getting some random reports of the NPE as below. Any suggestion? Unfortunately I can't replicate.

```
java.lang.NullPointerException
	at org.controlsfx.control.Notifications$NotificationPopupHandler.getScreenBounds(Notifications.java:364)
	at org.controlsfx.control.Notifications$NotificationPopupHandler.show(Notifications.java:343)
	at org.controlsfx.control.Notifications.show(Notifications.java:305)
	at org.controlsfx.control.Notifications.showInformation(Notifications.java:280)

```

thanks
nicola

**Comment by nicolabeghin** [comment]
At the moment I had to downgrade to the RC2

**Comment by abhinayagarwal** [comment]
@Ciruman Can this be caused because of #1130 ?

**Comment by Ciruman** [comment]
> @Ciruman Can this be caused because of #1130 ?

Yes, I think so. I will have a look.

**Comment by Ciruman** [comment]
Firstly, I found the error. ```Utils.getWindow(null)``` can return null. I will fix it now.

**Comment by nicolabeghin** [comment]
Thanks a lot!
