### ISSUE TITLE
 java.lang.IllegalAccessError: class impl.org.controlsfx.skin.BreadCrumbBarSkin (in module org.controlsfx.controls)

### ISSUE THREAD

**Issue by goxr3plus** [controlsfx/controlsfx#1161]
I am using controlsfx-11 with Java 11 and i am getting the below error : What i am doing wrong :) ?

Attaching the error below :

``` JAVA
Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class impl.org.controlsfx.skin.BreadCrumbBarSkin (in module org.controlsfx.controls) cannot access class com.sun.javafx.scene.traversal.ParentTraversalEngine (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.scene.traversal to module org.controlsfx.controls
	at org.controlsfx.controls/impl.org.controlsfx.skin.BreadCrumbBarSkin.fixFocusTraversal(BreadCrumbBarSkin.java:83)
	at org.controlsfx.controls/impl.org.controlsfx.skin.BreadCrumbBarSkin.<init>(BreadCrumbBarSkin.java:76)
	at org.controlsfx.controls/org.controlsfx.control.BreadCrumbBar.createDefaultSkin(BreadCrumbBar.java:318)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
```

**Comment by abhinayagarwal** [comment]
You can always get an idea of what JVM arguments to add by looking at the exception. Here, you need to add:

```
--add-exports=javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls
--add-exports=javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls
```

You can also check all the args used by ControlsFX in its [build.gradle](https://github.com/controlsfx/controlsfx/blob/9.0.0/build.gradle).

**Comment by goxr3plus** [comment]
Thank you very much ♥
