### ISSUE TITLE
JavaFX 12 GridView

### ISSUE THREAD

**Issue by sbruhse** [controlsfx/controlsfx#1166]
Hello! I have problems with the GridView on JavaFX 12 and Java 12. I just migrated from Java 8 to 12. If I am commenting out, everything is fine. I already found issues in you bitbucket, but they seemt to be closed and solved. Is there anything I could do wrong?
```
Exception in thread "JavaFX Application Thread" java.lang.reflect.InaccessibleObjectException: Unable to make field private final javafx.scene.control.skin.VirtualFlow javafx.scene.control.skin.VirtualContainerBase.flow accessible: module javafx.controls does not "opens javafx.scene.control.skin" to unnamed module @1a21d23b
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:341)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
	at impl.org.controlsfx.ReflectionUtils.getVirtualFlow(ReflectionUtils.java:157)
	at impl.org.controlsfx.skin.GridViewSkin.<init>(GridViewSkin.java:52)
	at org.controlsfx.control.GridView.createDefaultSkin(GridView.java:142)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9529)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:569)
	at javafx.graphics/javafx.scene.Scene.preferredSize(Scene.java:1745)
	at javafx.graphics/javafx.scene.Scene$2.preferredSize(Scene.java:393)
	at javafx.graphics/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics/javafx.stage.Window$12.invalidated(Window.java:1086)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics/javafx.stage.Window.setShowing(Window.java:1174)
	at javafx.graphics/javafx.stage.Window.show(Window.java:1189)
	at javafx.graphics/javafx.stage.Stage.show(Stage.java:273)
	at javafx.graphics/javafx.stage.Stage.showAndWait(Stage.java:463)
```

**Comment by abhinayagarwal** [comment]
Which version of ControlsFX are you using?

In case you are using 11, you need to pass the following JVM flag to your application:

```
--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls
```

**Comment by sbruhse** [comment]
Yes to both. I am

gradle.properties:
```
org.gradle.jvmargs="--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls"
```

Parts of my build.gradle:
```
plugins {
    id "java"
    id "application"
    id "jacoco"
    id "org.sonarqube" version "2.7"
    id 'org.openjfx.javafxplugin' version '0.0.7'
    id 'org.beryx.jlink' version '2.1.9'
}

repositories {
    // Use 'jcenter' for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    mavenLocal()
    mavenCentral()
    jcenter()
  	
}



javafx {
    version = '12'
    modules = [ 'javafx.controls', 'javafx.fxml', 'javafx.base', 'javafx.graphics', 'javafx.media', 'javafx.web']
}

// In this section you declare the dependencies for your production and test code
dependencies {
  	//classpath files("/usr/share/java/openjfx/lib/packager.jar")
	//classpath files("/usr/lib/jvm/java-8-openjdk-amd64/lib/ant-javafx.jar")
 
    // The production code uses the SLF4J logging API at compile time
    implementation 'de.saxsys:mvvmfx:1.8.0'
    implementation 'org.apache.logging.log4j:log4j-api:2.11.+'
    implementation 'org.apache.logging.log4j:log4j-core:2.11.+'
    implementation 'org.apache.logging.log4j:log4j-slf4j-impl:2.11.+'
    implementation 'com.google.code.gson:gson:2.8.+'
    implementation 'org.hibernate:hibernate-core:5.4.3.Final'
    implementation 'org.apache.commons:commons-lang3:3.+'
    implementation 'org.apache.derby:derby:10.14.+'
    implementation 'javax.measure:unit-api:2.0-EDR'
    implementation 'org.jscience:jscience:4.3.1'
    implementation 'com.google.guava:guava:27.1-jre'
    implementation 'org.controlsfx:controlsfx:11.0.0'
    implementation 'org.openjfx:javafx:12.0.+'

    // Declare the dependency for your favourite test framework you want to use in your tests.
    // TestNG is also supported by the Gradle Test task. Just change the
    // testCompile dependency to testCompile 'org.testng:testng:6.8.1' and add
    // 'test.useTestNG()' to your build script.
    testCompile 'junit:junit:4.+'
    testCompile 'org.testfx:testfx-core:4.0.15-alpha'
    testCompile 'org.testfx:testfx-junit:4.0.15-alpha'
    testCompile 'org.mockito:mockito-core:2.28.+'
    testCompile 'org.assertj:assertj-core:3.+'
}
```

**Comment by danielpeintner** [comment]
The log states

`module javafx.controls does not "opens javafx.scene.control.skin" to unnamed module`

Maybe give it a try adding `--add-opens` to `ALL-UNNAMED`

**Comment by sbruhse** [comment]
Thanks for the reply! :)

I tried this already.

**Comment by sbruhse** [comment]
I tried a bit more. Since the tool support for Java 12 seems not that good yet, I choosed to update to Java 11. Everything works fine, when I comment out the GridViews. But with the GridView I still get an error:
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final javafx.scene.control.skin.VirtualFlow javafx.scene.control.skin.VirtualContainerBase.flow accessible: module javafx.controls does not "opens javafx.scene.control.skin" to module org.controlsfx.controls
  at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:341)
  at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:281)
  at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
  at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
  at org.controlsfx.controls/impl.org.controlsfx.ReflectionUtils.getVirtualFlow(ReflectionUtils.java:157)
  at org.controlsfx.controls/impl.org.controlsfx.skin.GridViewSkin.<init>(GridViewSkin.java:52)
  at org.controlsfx.controls/org.controlsfx.control.GridView.createDefaultSkin(GridView.java:142)
  at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
  at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
  at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
  at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
  at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
  at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
  at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
  at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
  at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
  at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
  at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
  at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
  at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
  at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
  at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
  at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
  at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
  at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
  at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
  at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
  at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
  at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
  at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
  at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
  at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
  at javafx.controls/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
  at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:900)
  at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
  at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
  at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
  at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
  at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
  at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
  at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
  at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
  at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
  at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
  at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
  at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
```
I tried also to add all the arguments controlfx is using in the build.gradle (read about this somewhere), it didn't help. 🤔

**Comment by abhinayagarwal** [comment]
You are still initializing the `GridView` somewhere in your application. If you use `GridView` in an application with JDK 9+, you need to add the following JVM flag to the application:

```
--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls
```

That's what the exception is complaining about :)

**Comment by sbruhse** [comment]
Isn't what you are saying what I did in gradle with this line?
```
org.gradle.jvmargs="--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls"
```

**Comment by abhinayagarwal** [comment]
Nope! That property sets the JVM arg for the Gradle process.

To set JVM args for your application, use [jvmArgs](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:jvmArgs).

**Comment by sbruhse** [comment]
Oh shit...

I corrected and its running. Thank you for you patience with my stupidness and help! 👍

**Comment by quitusl** [comment]
I get the same error in a Maven project in Netbeans , how can i solved it ?

`Exception in thread "JavaFX Application Thread" java.lang.reflect.InaccessibleObjectException: Unable to make field private final javafx.scene.control.skin.VirtualFlow javafx.scene.control.skin.VirtualContainerBase.flow accessible: module javafx.controls does `

**Comment by nintendo-dave** [comment]
Good midnight alltogether :)
I'm having a similar issue. I can't find out why and how. I already tried to add the "--add-opens..." to the runconfiguration for the Intellij JVM.
The Error looks like this:
`Exception in thread "JavaFX Application Thread" java.lang.reflect.InaccessibleObjectException: Unable to make protected javafx.collections.ObservableList javafx.scene.Parent.getChildren() accessible: module javafx.graphics does not "opens javafx.`

**Comment by FelipeAumannRS** [comment]
> Nope! That property sets the JVM arg for the Gradle process.
> 
> To set JVM args for your application, use [jvmArgs](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:jvmArgs).

Great answer. Could you provide it for maven btw
