### ISSUE TITLE
AutoCompletionBinding throws IllegalAccessError

### ISSUE THREAD

**Issue by Folling** [controlsfx/controlsfx#1167]
The following code:
```java
        ComboBox<String> comboBox = new ComboBox<>();

        comboBox.setItems(FXCollections.observableArrayList("A", "B", "C", "D"));

        TextFields.bindAutoCompletion(comboBox.getEditor(), comboBox.getItems());
```

produces the following exception:

```
Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class org.controlsfx.control.textfield.AutoCompletionBinding (in unnamed module @0x30013df0) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to unnamed module @0x30013df0
	at org.controlsfx.control.textfield.AutoCompletionBinding.<init>(AutoCompletionBinding.java:522)
	at impl.org.controlsfx.autocompletion.AutoCompletionTextFieldBinding.<init>(AutoCompletionTextFieldBinding.java:107)
	at impl.org.controlsfx.autocompletion.AutoCompletionTextFieldBinding.<init>(AutoCompletionTextFieldBinding.java:92)
	at org.controlsfx.control.textfield.TextFields.bindAutoCompletion(TextFields.java:187)
```

**Comment by abhinayagarwal** [comment]
Are you using ControlsFX 9.0.0?

**Comment by Folling** [comment]
No I'm on the 11.0.0 release

**Comment by abhinayagarwal** [comment]
Please go through [Using ControlsFX with JDK 9 and above](https://github.com/controlsfx/controlsfx/wiki/%5BWIP%5D-Using-ControlsFX-with-JDK-9-and-above) and let us know if you can resolve the issue.

**Comment by Folling** [comment]
Ah I wasn't aware those extra steps were necessary. 
Thanks for pointing it out!
