### ISSUE TITLE
NullPointerException in VirtualFlow.findOwnerCell()

### ISSUE THREAD

**Issue by pvnhome** [controlsfx/controlsfx#1212]
Clone project and switch to v11.0.0 tag.

```
cd controlsfx-samples
gradle run
```

![g1](https://user-images.githubusercontent.com/9364110/68645090-2598b780-0541-11ea-8945-3439f593f74e.png)

![image](https://user-images.githubusercontent.com/9364110/68645291-c9826300-0541-11ea-820c-6a7b51ab66ea.png)

![image](https://user-images.githubusercontent.com/9364110/68645322-d8691580-0541-11ea-8599-c0956acb23f1.png)

![image](https://user-images.githubusercontent.com/9364110/68645333-e159e700-0541-11ea-94ce-61e842794515.png)

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at javafx.controls/javafx.scene.control.skin.VirtualFlow$3.findOwnerCell(VirtualFlow.java:645)
        at javafx.controls/javafx.scene.control.skin.VirtualFlow$3.select(VirtualFlow.java:619)
        at javafx.graphics/com.sun.javafx.scene.traversal.TraversalEngine.select(TraversalEngine.java:104)
        at javafx.graphics/com.sun.javafx.scene.traversal.TopMostTraversalEngine.trav(TopMostTraversalEngine.java:77)
        at javafx.graphics/javafx.scene.Scene.traverse(Scene.java:2092)
        at javafx.graphics/javafx.scene.Node.traverse(Node.java:8323)
        at javafx.graphics/javafx.scene.Node$1.traverse(Node.java:516)
        at javafx.graphics/com.sun.javafx.scene.NodeHelper.traverse(NodeHelper.java:236)
        at javafx.controls/com.sun.javafx.scene.control.behavior.FocusTraversalInputMap.traverse(FocusTraversalInputMap.java:98)
        at javafx.controls/com.sun.javafx.scene.control.behavior.FocusTraversalInputMap.traverseNext(FocusTraversalInputMap.java:138)
        at javafx.controls/com.sun.javafx.scene.control.behavior.FocusTraversalInputMap.lambda$static$4(FocusTraversalInputMap.java:53)
        at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
        at javafx.graphics/javafx.scene.Scene$KeyHandler.process(Scene.java:4058)
        at javafx.graphics/javafx.scene.Scene$KeyHandler.access$1500(Scene.java:4004)
        at javafx.graphics/javafx.scene.Scene.processKeyEvent(Scene.java:2121)
        at javafx.graphics/javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2595)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
        at javafx.graphics/com.sun.glass.ui.View.handleKeyEvent(View.java:547)
        at javafx.graphics/com.sun.glass.ui.View.notifyKey(View.java:971)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by abhinayagarwal** [comment]
I really like how the issue is described :+1:

**Comment by Maxoudela** [comment]
The stackTrace does not link to ControlsFX. So We'll have to dig to find if this is a regression on JavaFX side or a mis-use on our side.

Thanks for the clear issue description

**Comment by jchildress** [comment]
I have the same issue.  Any luck on finding/fixing the cause?

**Comment by samhutchins** [comment]
I've done some digging on this, and this small example will reproduce the issue:

```java
import org.controlsfx.control.CheckListView;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class BasicJavaFx
{
    public static void main(
        final String... args)
    {
        Application.launch(MainWindow.class);
    }

    public static class MainWindow extends Application
    {
        @Override
        public void start(final Stage primaryStage)
        {
            final var root = new BorderPane();

            final var list = new CheckListView<String>();

            list.getItems().addAll(
                "Hello", "There!");

            root.setCenter(list);

            final var scene = new Scene(root, 600, 400);
            primaryStage.setScene(scene);
            primaryStage.show();
        }

    }
}
```

If you run that then hit `tab`, `left`, or `right` the exception will be thrown.

In the constructor for `CheckListView.java` there's this code:

```java
setCellFactory(listView -> {
            final CheckBoxListCell<T> checkBoxListCell = new CheckBoxListCell<>(item -> getItemBooleanProperty(item));
            checkBoxListCell.focusedProperty().addListener((o, ov, nv) -> {
                if (nv) {
                    final Parent parent = checkBoxListCell.getParent();
                    if (parent != null) {
                        parent.requestFocus();
                    }
                }
            });
            return checkBoxListCell;
        });
```

If you remove the `parent.requestFocus()` line, the issue goes away. I'm curious as to why you perform a request focus there, as it results in the selection being greyed out while navigating with a keyboard. Here are some screenshots:

With `requestFocus()`
![Screenshot 2020-07-29 at 10 30 20](https://user-images.githubusercontent.com/13986933/88783433-ac043080-d186-11ea-93b9-b5d7cd25bab8.png)


Without `requestFocus()`
![Screenshot 2020-07-29 at 10 30 07](https://user-images.githubusercontent.com/13986933/88783442-b1fa1180-d186-11ea-93ce-0ffc1ad54381.png)


My temptation, not being overly familiar with the code, would be to simply remove the listener on the cell's `focusedProperty` and reduce the whole `cellFactory` to this: 
```java
setCellFactory(lv -> new CheckBoxListCell<T>(item -> getItemBooleanProperty(item)));
```

If the `requestFocus()` line is required for some reason I don't yet see, more investigation will probably be required.
