### ISSUE TITLE
NPE in CheckListView

### ISSUE THREAD

**Issue by samhutchins** [controlsfx/controlsfx#1219]
I'm afraid I can't reproduce this, but it's something we've seen in the wild. Here's a stack trace:

```
java.lang.NullPointerException
	at org.controlsfx.control.CheckListView.lambda$null$2(CheckListView.java:127)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyBooleanPropertyBase.fireValueChangedEvent(ReadOnlyBooleanPropertyBase.java:72)
	at javafx.scene.Node$FocusedProperty.notifyListeners(Node.java:7720)
	at javafx.scene.Node.setFocused(Node.java:7773)
	at javafx.scene.control.ListCell.updateFocus(ListCell.java:526)
	at javafx.scene.control.ListCell.indexChanged(ListCell.java:332)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
	at com.sun.javafx.scene.control.skin.VirtualFlow.setCellIndex(VirtualFlow.java:1952)
	at com.sun.javafx.scene.control.skin.VirtualFlow.getPrivateCell(VirtualFlow.java:1847)
	at com.sun.javafx.scene.control.skin.ListViewSkin.queryAccessibleAttribute(ListViewSkin.java:531)
	at javafx.scene.control.Control.queryAccessibleAttribute(Control.java:917)
	at javafx.scene.control.ListView.queryAccessibleAttribute(ListView.java:1079)
	at javafx.scene.Node$19.getAttribute(Node.java:9648)
	at com.sun.glass.ui.Accessible$GetAttribute.run(Accessible.java:142)
	at java.security.AccessController.doPrivileged(AccessController.java)
	at com.sun.glass.ui.Accessible.lambda$getAttribute$4(Accessible.java:169)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.glass.ui.Accessible.getAttribute(Accessible.java:166)
	at com.sun.glass.ui.mac.MacAccessible.sendNotification(MacAccessible.java:719)
	at javafx.scene.Scene$13.invalidated(Scene.java:2094)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:111)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.Scene$KeyHandler.setFocusOwner(Scene.java:3933)
	at javafx.scene.Scene$KeyHandler.requestFocus(Scene.java:3980)
	at javafx.scene.Scene$KeyHandler.access$1900(Scene.java:3919)
	at javafx.scene.Scene.requestFocus(Scene.java:2044)
	at javafx.scene.Node.requestFocus(Node.java:7881)
	at com.sun.javafx.scene.control.skin.ListViewSkin.lambda$new$367(ListViewSkin.java:117)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:282)
	at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:223)
	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
	at com.sun.javafx.scene.control.skin.VirtualFlow.lambda$new$2(VirtualFlow.java:526)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3494)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(AccessController.java)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
```

We've seen it on macOS 10.14.6, using JavaFX 8 and ControlsFX 8.40.15 (Oracle JRE 8u161, FWIW)

It looks like a `CheckBoxListCell` is firing a change on the focusedProperty in a state when that cell's `getParent` method returns `null`.

**Comment by Maxoudela** [comment]
Thanks for the issue report. Are you able to provide a PR for that? 

We could indeed check if the Parent is null before trying to access it. Kind of a blind fix but it does not shock me.

**Comment by samhutchins** [comment]
@Maxoudela I've opened #1222 

I also seem to have created a bunch of these "commit that referenced this issue" entries, my apologies. It took me a few attempts to get the line endings correct
