### ISSUE TITLE
InaccessibleObjectException when creating Glyph

### ISSUE THREAD

**Issue by tkslaw** [controlsfx/controlsfx#1245]
When JavaFX is on the module-path, simply creating a `Glyph` throws the following exception:

```none
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Exception in Application start method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.util.ServiceConfigurationError: org.controlsfx.glyphfont.GlyphFont: Provider org.controlsfx.glyphfont.FontAwesome could not be instantiated
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:584)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:806)
        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:724)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1396)
        at org.controlsfx.controls/org.controlsfx.glyphfont.GlyphFontRegistry.<clinit>(GlyphFontRegistry.java:67)
        at org.controlsfx.controls/org.controlsfx.glyphfont.Glyph.setFontFamily(Glyph.java:250)
        at org.controlsfx.controls/org.controlsfx.glyphfont.Glyph.<init>(Glyph.java:134)
        at org.controlsfx.controls/org.controlsfx.glyphfont.Glyph.create(Glyph.java:83)
        at app/com.example.app.Main.start(Main.java:13)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        ... 1 more
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:782)
        ... 16 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public static com.sun.javafx.css.StyleManager com.sun.javafx.css.StyleManager.getInstance() accessible: module javafx.graphics does not "exports com.sun.javafx.css" to module org.controlsfx.controls
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:349)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:289)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:196)
        at java.base/java.lang.reflect.Method.setAccessible(Method.java:190)
        at org.controlsfx.controls/impl.org.controlsfx.ReflectionUtils.addUserAgentStylesheet(ReflectionUtils.java:225)
        at org.controlsfx.controls/org.controlsfx.glyphfont.GlyphFont.<clinit>(GlyphFont.java:57)
        ... 22 more
```

---

## Example Code

module-info.java:

```java
module app {
  requires org.controlsfx.controls;

  exports com.example.app to
      javafx.graphics;
}
```

Main.java:

```java
package com.example.app;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import org.controlsfx.glyphfont.Glyph;

public class Main extends Application {

  @Override
  public void start(Stage primaryStage) {
    Glyph glyph = Glyph.create("FontAwesome|Gear"); // exception thrown here
    primaryStage.setScene(new Scene(new StackPane(glyph), 300, 150));
    primaryStage.show();
  }
}
```

Command line:

```none
java -p $mods -m app/com.example.app.Main
```

Where `$mods` is a path containing the `javafx.base`, `javafx.graphics`, `javafx.controls`, `org.controlsfx.controls`, and `app` modules. All except the `app` module (which must be compiled from the above code) were taken from Maven Central.

### Versions

Library         |    Version
 :---:             |   :---:
Java             | AdoptOpenJDK 14
JavaFX         | OpenJFX 14
ControlsFX  | 11.0.1

### Workaround

Use:

```none
--add-exports javafx.graphics/com.sun.javafx.css=org.controlsfx.controls
```

**Comment by abhinayagarwal** [comment]
This is currently a shortcoming of using ControlsFX with JDK9+. For more information please check the Wiki: [Using ControlsFX with JDK 9 and above](https://github.com/controlsfx/controlsfx/wiki/%5BWIP%5D-Using-ControlsFX-with-JDK-9-and-above)

**Comment by tkslaw** [comment]
Thanks for pointing out that part of the Wiki, I hadn't noticed it before. That said, may I ask why `GlyphFont` needs this?

```java
static {
    ReflectionUtils.addUserAgentStylesheet(
            GlyphFont.class.getResource("glyphfont.css").toExternalForm()); //$NON-NLS-1$
}
```

Looking at the referenced CSS file, it simply contains:

```css
.glyph-font {

}

.glyph-font.gradient{
    -fx-effect: innershadow( three-pass-box , derive(-fx-text-fill,-70%) , 0.1em, 0.0 , 0.07em, 0.07em );
}

.glyph-font.hover-effect:hover{
    -fx-effect: dropshadow( three-pass-box , derive(-fx-text-fill,0%) , 0.01em, 0.0 , 0, 0);
}

.glyph-font.hover-effect:selected{
    -fx-effect: dropshadow( three-pass-box , derive(-fx-text-fill,0%) , 0.01em, 0.0 , 0, 0);
}
```

Why does that stylesheet need to be added via the `com.sun.javafx.css.StyleManager` class? I wonder if overriding [`Region#getUserAgentStylesheet()`][1]  (added in JavaFX 8u40) in the `Glyph` class would not be more appropriate? The documentation of that method mentions:

>An implementation may specify its own user-agent styles for this Region, and its children, by overriding this method. These styles are used in addition to whatever user-agent stylesheets are in use. **This provides a mechanism for third parties to introduce styles for custom controls** _[emphasis added]_.
>
>_[...]_

For example:

```java
package org.controlsfx.glyphfont;

// imports...

public class Glyph extends Label implements Duplicatable<Glyph> {

   // ...

    @Override
    public String getUserAgentStylesheet() {
        return Glyph.class.getResource("glyphfont.css").toExternalForm();
    }

    // ...
}
```

  [1]: https://openjfx.io/javadoc/14/javafx.graphics/javafx/scene/layout/Region.html#getUserAgentStylesheet()

**Comment by abhinayagarwal** [comment]
Hi @tkslaw,

Thank you for the comment. It does make sense. Can you please test and raise a PR to the 9.0.0 branch, if it works?

**Comment by tkslaw** [comment]
@abhinayagarwal 

How should a test for this be implemented? I couldn't find existing tests related to `Glyph` / `GlyphFont`.

**Comment by abhinayagarwal** [comment]
A simple JUnit test where the Glyph is loaded successfully from `Glyph.create("FontAwesome|Gear");` without the need of reflection should be enough for now.

**Comment by abhinayagarwal** [comment]
Hi @tkslaw,

I had forgotten that the test module on `9.0.0` branch is still broken. I need to fix it.. someday. Can you just a PR with the fix?
