### ISSUE TITLE
java.lang.IllegalAccessError when usind controlsfx with JavaFX in Java 11

### ISSUE THREAD

**Issue by kaiffeetasse** [controlsfx/controlsfx#1267]
I am trying to use org.controlsfx.control.textfield.AutoCompletionBinding along with JavaFX in Java 11. This is my maven dependency:

```
<dependency>
        <groupId>org.controlsfx</groupId>
        <artifactId>controlsfx</artifactId>
        <version>11.0.1</version>
</dependency>
```

And my module-info.java:

```
open module gui {
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.base;
    requires javafx.graphics;

    requires org.controlsfx.controls;
}
```

```
Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class org.controlsfx.control.textfield.AutoCompletionBinding (in module org.controlsfx.controls) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to module org.controlsfx.controls
	at org.controlsfx.controls/org.controlsfx.control.textfield.AutoCompletionBinding.<init>(AutoCompletionBinding.java:525)
	at org.controlsfx.controls/impl.org.controlsfx.autocompletion.AutoCompletionTextFieldBinding.<init>(AutoCompletionTextFieldBinding.java:107)
	at org.controlsfx.controls/impl.org.controlsfx.autocompletion.AutoCompletionTextFieldBinding.<init>(AutoCompletionTextFieldBinding.java:92)
	at org.controlsfx.controls/org.controlsfx.control.textfield.TextFields.bindAutoCompletion(TextFields.java:187)
	at gui/de.markant.mase.gui.department.edit.DepartmentEditGUIController.initSupervisor(DepartmentEditGUIController.java:140)
	at gui/de.markant.mase.gui.department.edit.DepartmentEditGUIController.init(DepartmentEditGUIController.java:94)
	at gui/de.markant.mase.gui.department.edit.DepartmentEditGUI.<init>(DepartmentEditGUI.java:31)
	at gui/de.markant.mase.gui.department.DepartmentGUIController.openEdit(DepartmentGUIController.java:175)
	at gui/de.markant.mase.gui.department.DepartmentGUIController.lambda$initButtonListeners$5(DepartmentGUIController.java:98)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1849)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by wirew0rm** [comment]
There is this [wiki page](https://github.com/controlsfx/controlsfx/wiki/Using-ControlsFX-with-JDK-9-and-above#autocompletionbinding) for debugging these kinds of errors, which might help you.

**Comment by rbi** [comment]
I just ran into the same issue. I've read the wiki page that says that you should add "--add-exports=javafx.base/com.sun.javafx.event=org.controlsfx.controls" to your command line. That isn't a nice option as I don't require any other command line options for my application yet. It prevents me from having "right-click > Run As > Java Application" in my IDE work out of the box.

Maybe ControlsFX could just fork `com.sun.javafx.event.EventHandlerManager` to get rid of depending on internal JavaFX API?

**Comment by abhinayagarwal** [comment]
Hi @rbi,

Yes that is a valid solution. Would you be willing to create a PR for the same?

**Comment by rbi** [comment]
Maybe if I find some time but I can't promise anything. If someone else want's to jump in I wouldn't mind.

**Comment by Siedlerchr** [comment]
Still an issue with javafx18 and jdk18 and controlsfx11

**Comment by pitzzahh** [comment]
Still an issue with Jdk 19 and latest realease when using AutoCompletionBinding 
```java
Caused by: java.lang.IllegalAccessError: class org.controlsfx.control.textfield.AutoCompletionBinding (in module org.controlsfx.controls) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to module org.controlsfx.controls
	at org.controlsfx.controls@11.1.2/org.controlsfx.control.textfield.AutoCompletionBinding.<init>(AutoCompletionBinding.java:538)
	at org.controlsfx.controls@11.1.2/impl.org.controlsfx.autocompletion.AutoCompletionTextFieldBinding.<init>(AutoCompletionTextFieldBinding.java:107)
	at org.controlsfx.controls@11.1.2/impl.org.controlsfx.autocompletion.AutoCompletionTextFieldBinding.<init>(AutoCompletionTextFieldBinding.java:92)
	at org.controlsfx.controls@11.1.2/org.controlsfx.control.textfield.TextFields.bindAutoCompletion(TextFields.java:188)
	at org.controlsfx.controls@11.1.2/org.controlsfx.control.textfield.TextFields.bindAutoCompletion(TextFields.java:182)
	at io.github.pitzzahh.atm.gui/io.github.pitzzahh.atmGui.controllers.AdminController.oneKeyTyped(AdminController.java:192)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 37 more
```

**Comment by pitzzahh** [comment]
> There is this [wiki page](https://github.com/controlsfx/controlsfx/wiki/Using-ControlsFX-with-JDK-9-and-above#autocompletionbinding) for debugging these kinds of errors, which might help you.

This actually fixed it. Thank you very much, sorry for being dumb.

**Comment by michaelsiame** [comment]
yes the wiki tutorial actually worked here are the steps for anyone else facing the same problem 

Open the IntelliJ IDEA project.

Navigate to the Run/Debug Configurations:

Click on the drop-down menu near the top-right corner (next to the run and debug buttons).
Select Edit Configurations.
In the Run/Debug Configurations dialog, find your JavaFX application configuration.

Under the Configuration tab, find the VM options field.

Add your --add-exports option to the VM options.

--add-exports=javafx.base/com.sun.javafx.event=org.controlsfx.controls

Click OK to save the configuration.

Run your JavaFX application using the modified configuration.
