### ISSUE TITLE
ControlsFX 11.0.1: nable to make protected javafx.collections.ObservableList javafx.scene.Parent.getChildren()

### ISSUE THREAD

**Issue by initialflame** [controlsfx/controlsfx#1281]
I've added all Exports described in my Manifest.MF (I'am runnning Java 11 efxclipse Application) Bu im Getting this Error (see below) and i don't know whats the Reason and "javafx.graphics/javafx.scene" is exported. 

<Java-Module-AddExports>javafx.graphics/javafx.scene=.,javafx.graphics/javafx.css=.,javafx.controls/javafx.scene.control=.,javafx.base/javafx.event=.,javafx.base/javafx.collections=.,javafx.graphics/com.sun.javafx.scene=.,javafx.graphics/com.sun.javafx.scene.traversal=.,javafx.controls/com.sun.javafx.scene.control.behavior=.,javafx.controls/com.sun.javafx.scene.control=.,javafx.controls/com.sun.javafx.scene.control.inputmap=.,javafx.base/com.sun.javafx.event=.,javafx.base/com.sun.javafx.collections=.,javafx.base/com.sun.javafx.runtime=.,javafx.graphics/com.sun.javafx.css=.,javafx.graphics/com.sun.javafx.application=.,javafx.graphics/com.sun.glass.ui=.,javafx.controls/javafx.scene.control.skin=.</Java-Module-AddExports>

`java.lang.reflect.InaccessibleObjectException: Unable to make protected javafx.collections.ObservableList javafx.scene.Parent.getChildren() accessible: module javafx.graphics does not "opens javafx.scene" to unnamed module @54a3821a
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:198)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:192)
	at impl.org.controlsfx.ImplUtils.getChildrenReflectively(ImplUtils.java:148)
	at impl.org.controlsfx.ImplUtils.getChildren(ImplUtils.java:125)
	at org.controlsfx.control.decoration.GraphicDecoration.applyDecoration(GraphicDecoration.java:115)
	at impl.org.controlsfx.skin.DecorationPane.showDecoration(DecorationPane.java:74)
	at impl.org.controlsfx.skin.DecorationPane.addAllDecorationsOnNode(DecorationPane.java:119)
	at impl.org.controlsfx.skin.DecorationPane.updateDecorationsOnNode(DecorationPane.java:70)
	at org.controlsfx.control.decoration.Decorator.lambda$updateDecorationsOnNode$0(Decorator.java:165)
	at org.controlsfx.control.decoration.Decorator.lambda$getDecorationPane$1(Decorator.java:205)
	at org.controlsfx.control.decoration.Decorator$1.invalidated(Decorator.java:223)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:348)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.base/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.graphics/javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1054)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1114)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:769)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:769)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:769)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent.scenesChanged(Parent.java:769)
	at javafx.graphics/javafx.scene.Node.invalidatedScenes(Node.java:1076)
	at javafx.graphics/javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.graphics/javafx.scene.Parent$2.onChanged(Parent.java:369)
	at javafx.base/com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.base/javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.base/javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.base/javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.base/javafx.collections.ModifiableObservableListBase.addAll(ModifiableObservableListBase.java:102)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:237)
	at javafx.base/com.sun.javafx.collections.VetoableListDecorator.addAll(VetoableListDecorator.java:103)
	at javafx.controls/javafx.scene.control.skin.ScrollPaneSkin.initialize(ScrollPaneSkin.java:705)
	at javafx.controls/javafx.scene.control.skin.ScrollPaneSkin.<init>(ScrollPaneSkin.java:266)
	at javafx.controls/javafx.scene.control.ScrollPane.createDefaultSkin(ScrollPane.java:634)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.controls/javafx.scene.control.Control.access$000(Control.java:83)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Parent.doProcessCSS(Parent.java:1397)
	at javafx.graphics/javafx.scene.Parent.access$400(Parent.java:79)
	at javafx.graphics/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9529)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Node.processCSS(Node.java:9522)
	at javafx.graphics/javafx.scene.Scene.doCSSPass(Scene.java:569)
	at javafx.graphics/javafx.scene.Scene.access$3400(Scene.java:172)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2477)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by abhinayagarwal** [comment]
I am not well versed with exporting packages from MANIFEST file.

Why are you trying to access  `javafx.scene.Parent.getChildren()` ?

**Comment by BowgartField** [comment]
> I am not well versed with exporting packages from MANIFEST file.
> 
> Why are you trying to access `javafx.scene.Parent.getChildren()` ?

No he don't try to acces `javafx.scene.Parent.getChildren()`. It's controlfx which try to access it. 
I got the same problem and i don't found a solution.
As for me, i just add Validation to my TextField and got this error.

**Comment by workerhn** [comment]
I have the update 11.0.2 and this problem persists when I use the ValidationSupport class.

**Comment by DaveJarvis** [comment]
A few more details about this issue. In the following code, uncommenting the line that adds a `VBox` to the `WizardPane`'s `BorderPane` causes this failure in [ControlsFX 11.1.2](https://github.com/DaveJarvis/keenwrite/blob/d641a0f3bb5f98dd61866c1ce81b058f7954486e/build.gradle#L69):

``` java
//border.setTop( stepsPane );
```

See [TypesetterInstaller.java](https://github.com/DaveJarvis/keenwrite/blob/d641a0f3bb5f98dd61866c1ce81b058f7954486e/src/main/java/com/keenwrite/typesetting/TypesetterInstaller.java#L131) for details.

**Comment by DaveJarvis** [comment]
Adding the `spacer()` is problematic:

```
  private Node spacer() {
    final var spacer = new Region();
    spacer.setPrefHeight( PAD );

    return spacer;
  }
```

Without call to `spacer()`, the exception no longer occurs.
