### ISSUE TITLE
ConcurrentModificationException on validationSupport.controls

### ISSUE THREAD

**Issue by shollander** [controlsfx/controlsfx#1284]
The `ObservableSet<Control>` field in `ValidationSupport` is not thread safe. I frequently receive `ConcurrentModificationException`s like this.

```
Exception in thread "JavaFX Application Thread" java.util.ConcurrentModificationException
    at java.base/java.util.HashMap$HashMapIterator.nextNode(HashMap.java:1493)
    at java.base/java.util.HashMap$HashMapIterator.next(HashMap.java:1516)
    at com.sun.javafx.collections.ObservableSetWrapper$1.next(ObservableSetWrapper.java:219)
    at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1047)
    at org.controlsfx.validation.ValidationSupport.redecorate(ValidationSupport.java:151)
    at org.controlsfx.validation.ValidationSupport.lamda$new$0(ValidationSupport.java:125)
    at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
...
```

**Comment by eugener** [comment]
You probably removing or adding nodes during iteration. 
Try to collect all the nodes you want to change  and do it once you finished iterating.

**Comment by shollander** [comment]
It is not my code that is doing the iteration. It is caused by some event.
