### ISSUE TITLE
IndexOutOfBoundsException while clearing SearchableComboBox

### ISSUE THREAD

**Issue by mkpaz** [controlsfx/controlsfx#1320]
Clearing SearchableComboBox items almost always leads to IndexOutOfBoundsException.

```
Exception in thread "JavaFX Application Thread" java.util.NoSuchElementException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.AbstractList$Itr.next(AbstractList.java:377)
	at java.base/java.util.AbstractList.indexOf(AbstractList.java:188)
	at javafx.controls/javafx.scene.control.ComboBox.lambda$new$1(ComboBox.java:245)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at javafx.base/javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:72)
	at javafx.base/com.sun.javafx.binding.BidirectionalBinding$TypedGenericBidirectionalBinding.changed(BidirectionalBinding.java:585)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
```

#### How to reproduce

Run this code and try to clear SearchableComboBox several times. In the 90% it will raise exception. Clearing normal combobox does not produce any error.

```java
public class Launcher extends Application {

    VBox vbox;
    Button populateBtn;

    SearchableComboBox<String> searchableComboBox;
    ObservableList<String> searchableBase = FXCollections.observableArrayList();
    Button clearSearchableBtn;

    ComboBox<String> filteredComboBox;
    ObservableList<String> filteredBase = FXCollections.observableArrayList();
    Button clearFilteredBtn;

    @Override
    public void start(Stage primaryStage) throws Exception {
        vbox = new VBox();

        searchableComboBox = new SearchableComboBox<>(searchableBase);
        searchableBase.setAll(getItems());
        searchableComboBox.getSelectionModel().selectLast();
        searchableComboBox.setPrefWidth(200);

        clearSearchableBtn = new Button("Clear searchable");
        clearSearchableBtn.setOnAction(event -> {
            Platform.runLater(() -> {
                // don't really matter
                // searchableComboBox.getSelectionModel().clearSelection();
                searchableBase.clear();
            });
        });

        filteredComboBox = new ComboBox<>(new FilteredList<>(filteredBase, val -> true));
        filteredBase.setAll(getItems());
        filteredComboBox.getSelectionModel().selectLast();
        filteredComboBox.setPrefWidth(200);

        clearFilteredBtn = new Button("Clear filtered");
        clearFilteredBtn.setOnAction(event -> {
            Platform.runLater(() -> {
                filteredBase.clear();
            });
        });

        populateBtn = new Button("Populate");
        populateBtn.setOnAction(event -> {
            searchableBase.setAll(getItems());
            searchableComboBox.getSelectionModel().selectLast();
            filteredBase.setAll(getItems());
            filteredComboBox.getSelectionModel().selectLast();
        });

        vbox.getChildren().addAll(
                searchableComboBox, clearSearchableBtn,
                filteredComboBox, clearFilteredBtn,
                populateBtn
        );
        vbox.setSpacing(10);
        Scene scene = new Scene(vbox, 400, 400);
        primaryStage.setTitle("Demo");
        primaryStage.setScene(scene);
        primaryStage.setOnCloseRequest(t -> Platform.exit());
        primaryStage.show();
    }

    private static List<String> getItems() {
        return List.of("test1", "test2", "foo");
    }
}
```

It may be a [similar issue](https://stackoverflow.com/a/27773466/7421700) except `Platform.runLater()` doesn't make any difference.  The only thing that helps is setting a new observable list each time you want to update items, which I'd want to avoid, because it resets bindings.

**Comment by danielpeintner** [comment]
I can confirm the problem but I do not really understand *why* `indexOf()` can throw `NoSuchElementException` in the following line https://github.com/openjdk/jfx/blob/dd22cd2d97d4bfc305e44f2e77b4c104c62ff31f/modules/javafx.controls/src/main/java/javafx/scene/control/ComboBox.java#L245

The same code changing `SearchableComboBox` to `ComboBox` works just fine.

**Comment by mkpaz** [comment]
I assume this lib is unmaintained. Closing as not interested.

**Comment by danielpeintner** [comment]
What comes to my mind is “Free as in beer”...
ControlsFX is a free open source library given to you at no cost and you should not have any expectations.

Having said that, I believe everyone is welcome to contribute and to improve

**Comment by abhinayagarwal** [comment]
This issue is existent as reported here https://github.com/controlsfx/controlsfx/issues/930#issuecomment-804643722

**Comment by Auriga2** [comment]
Thanks for reopening the issue.

**Comment by KenobySky** [comment]
I just faced this exact issue.

**Comment by Auriga2** [comment]
As a workaround, adding the new list in an `observableArrayList` and setting it as below fixed the issue for me.
```
final ObservableList<ParameterValue> options = FXCollections.observableArrayList();
options.setAll(<Add the new list here);
searchableComboBox.setItems(options);
```

**Comment by SolydBoy** [comment]
Hey 
I think you should use the itemProperty and do a setValue on that. 
Something like that:

```kotlin
comboBox.itemsProperty().setValue(FXCollections.observableList(authorizedValues))
```
