### ISSUE TITLE
Fix for issue 1038 introduced a new bug

### ISSUE THREAD

**Issue by mkarneim** [controlsfx/controlsfx#1324]
With the fix for issue #1038 I accidentally itroduced another bug.
I am very sorry.

This bug causes errors like this:
```
java.lang.RuntimeException: BorderPane.maxWidth : A bound value cannot be set.
	at javafx.beans.property.DoublePropertyBase.set(DoublePropertyBase.java:144)
	at javafx.css.StyleableDoubleProperty.set(StyleableDoubleProperty.java:82)
	at javafx.scene.layout.Region.setMaxWidth(Region.java:1273)
	at impl.org.controlsfx.ImplUtils.injectAsRootPane(ImplUtils.java:60)
	at org.controlsfx.control.decoration.Decorator.lambda$getDecorationPane$1(Decorator.java:199)
	at org.controlsfx.control.decoration.Decorator.getDecorationPane(Decorator.java:215)
	at org.controlsfx.control.decoration.Decorator.updateDecorationsOnNode(Decorator.java:165)
	at org.controlsfx.control.decoration.Decorator.removeDecoration(Decorator.java:119)
	at org.controlsfx.validation.decoration.AbstractValidationDecoration.removeDecorations(AbstractValidationDecoration.java:75)
```

To fix the bug, the following lines which I added to class `ImplUtils` 
https://github.com/controlsfx/controlsfx/blob/c60656b4f360d530b17ef49663a853f76807035b/controlsfx/src/main/java/impl/org/controlsfx/ImplUtils.java#L57-L62

should be replaced with this:
```java
  if (injectedParent instanceof Region) { 
     Region region = (Region) injectedParent; 
  
     region.setMaxWidth(Double.MAX_VALUE); 
     region.setMaxHeight(Double.MAX_VALUE); 
   } 
```
in order assign the `injectedParent` to the `region` variable instead of the `originalParent`.

This issue affects all controls-fx versions from version 8 to the lastest one.

**Comment by abhinayagarwal** [comment]
Hi @mkarneim ,

Can you open a PR for this?

**Comment by mkarneim** [comment]
> Hi @mkarneim ,
> 
> Can you open a PR for this?

Yes, of course.

Do you want only one PR for your master branch or multiple PRs for all affected versions?

**Comment by abhinayagarwal** [comment]
`master` (JDK 8) is not under active development. Please target all PRs to `jfx-13` branch.

**Comment by mkarneim** [comment]
> `master` (JDK 8) is not under active development. Please target all PRs to `jfx-13` branch.

Done.

Will this be backported to controlsfx 8.40.*, 9.* and 11.0.*?

**Comment by abhinayagarwal** [comment]
There will be no more updates to ControlsFX 8.x. These changes will be released as a part of 11.x.

**Comment by mkarneim** [comment]
Alright, thanks.
