### ISSUE TITLE
MasterDetailPane setDividerPosition does not work as expected

### ISSUE THREAD

**Issue by bendardenne** [controlsfx/controlsfx#1325]
There seems to be no way to assign a divider position early. After "a while" (a few rendering pulses?) this ends up working (if e.g. you bind the setDividerPosition call to a button), but it's not clear when and there seems to be no reliable to set this at application startup.

```java
  @Override
  public void start( Stage aStage ) throws Exception {

    ListView<String> mainList = new ListView<>( FXCollections.observableArrayList( "Hello", "hi" ) );
    ListView<String> secondaryList = new ListView<>( FXCollections.observableArrayList( "content", "content" ) );

    MasterDetailPane centerPane = new MasterDetailPane( Side.LEFT, mainList, secondaryList, true );

    aStage.showingProperty().addListener( new ChangeListener<Boolean>() {
      @Override
      public void changed( ObservableValue<? extends Boolean> aValue, Boolean aBoolean, Boolean aT1 ) {
        centerPane.setDividerPosition( 0.5 );
      }
    } );

    aStage.setScene( new Scene( centerPane ) );
    aStage.show();
  }

```

**Comment by dlemmermann** [comment]
Try turning off the animation support, set the position, then re-enable animation. I think that's what worked for me.

**Comment by bendardenne** [comment]
Do you mean MasterDetailPane#setAnimated? Do you have an example? Turning it off doesn't seem to do anything for me.


```java
    centerPane.setAnimated( false );
    aStage.showingProperty().addListener( ( aValue, aBoolean, aT1 ) -> {
      centerPane.setDividerPosition( 0.5 );
    } );

    aStage.setScene( new Scene( centerPane ) );
    aStage.show();
```

**Comment by dlemmermann** [comment]
Now try to set the position directly after setAnimated(false), and not inside the listener.

**Comment by bendardenne** [comment]
It's somehow "closer" to 0.5, but still wrong. This tells me something else is changing the position later. 

```java

  public void start( Stage aStage ) throws Exception {
    ListView<String> mainList = new ListView<>( FXCollections.observableArrayList( "Hello", "hi" ) );
    ListView<String> secondaryList = new ListView<>( FXCollections.observableArrayList( "content", "content" ) );
    MasterDetailPane centerPane = new MasterDetailPane( Side.LEFT, mainList, secondaryList, true );

    centerPane.dividerPositionProperty().addListener( ( aValue, aNumber, aT1 ) -> {
      System.out.println( aT1 );
    } );

    centerPane.setAnimated( false );
    centerPane.setDividerPosition( 0.5 );

    aStage.setScene( new Scene( centerPane ) );
    aStage.show();
  }

```

**Comment by bendardenne** [comment]
Taking a stacktrace, this what changes the position to 0.13 after my manual call to setDividerPosition(0.5)


	  at javafx.scene.control.SplitPane$Divider.setPosition(SplitPane.java:501)
	  at javafx.scene.control.skin.SplitPaneSkin.setAbsoluteDividerPos(SplitPaneSkin.java:696)
	  at javafx.scene.control.skin.SplitPaneSkin.setupContentAndDividerForLayout(SplitPaneSkin.java:888)
	  at javafx.scene.control.skin.SplitPaneSkin.layoutChildren(SplitPaneSkin.java:396)
	  at javafx.scene.control.Control.layoutChildren(Control.java:601)
	  at javafx.scene.Parent.layout(Parent.java:1204)
	  at javafx.scene.Parent.layout(Parent.java:1211)
	  at javafx.scene.Scene.doLayoutPass(Scene.java:576)
	  at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)
	  at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	  at com.sun.javafx.tk.Toolkit$$Lambda$392.1985477940.run(Unknown Source:-1)
	  at java.security.AccessController.doPrivileged(AccessController.java:-1)
	  at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	  at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)

**Comment by dlemmermann** [comment]
Beats me ... you might wanna go with a Platform.runLater(() -> masterDetailPane.setDividerPosition(.5)).

**Comment by bendardenne** [comment]
Yeah I thought of that too but it doesn't work. 

I have the feeling that both this issue and #1323 is because of SplitPane and its buggy implementation.
