### ISSUE TITLE
Exception ControlsFx 11.0.3

### ISSUE THREAD

**Issue by Hugolarson** [controlsfx/controlsfx#1327]
java.lang.reflect.InaccessibleObjectException: Unable to make field private final javafx.scene.control.skin.VirtualFlow javafx.scene.control.skin.VirtualContainerBase.flow accessible: module javafx.controls does not "opens javafx.scene.control.skin" to unnamed module @357c9d92
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:301)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at impl.org.controlsfx.ReflectionUtils.getVirtualFlow(ReflectionUtils.java:181)
	at impl.org.controlsfx.skin.GridViewSkin.<init>(GridViewSkin.java:52)
	at org.controlsfx.control.GridView.createDefaultSkin(GridView.java:142)
	at javafx.controls/javafx.scene.control.Control.doProcessCSS(Control.java:897)
	at javafx.controls/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:145)

**Comment by abhinayagarwal** [comment]
This is expected. Please add the following JVM flag to your application:

```
--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls
```

**Comment by abhinayagarwal** [comment]
FYI, I have opened #1330 to resolve this in future release.
