### ISSUE TITLE
NullPointerException in CheckListView when emptying item list

### ISSUE THREAD

**Issue by r-smirnov** [controlsfx/controlsfx#1354]
Any operation on CheckListView embedded in Swing GUI, where item list becomes empty, results in an exception:
```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at javafx.scene.control.skin.VirtualFlow$3.findOwnerCell(VirtualFlow.java:645)
	at javafx.scene.control.skin.VirtualFlow$3.select(VirtualFlow.java:619)
	at com.sun.javafx.scene.traversal.TraversalEngine.select(TraversalEngine.java:104)
	at com.sun.javafx.scene.traversal.TopMostTraversalEngine.trav(TopMostTraversalEngine.java:77)
	at javafx.scene.Scene.traverse(Scene.java:2092)
	at javafx.scene.Scene.focusIneligible(Scene.java:2111)
	at javafx.scene.Scene.access$3100(Scene.java:172)
	at javafx.scene.Scene$ScenePulseListener.focusCleanup(Scene.java:2447)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2462)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:519)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Version: 11.1.0

To reproduce, click the button of this test case:
```java
import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import org.controlsfx.control.CheckListView;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;

public class CheckListViewSwingTest {
    private static CheckListView<String> checkListView;

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame();
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            JFXPanel panel = new JFXPanel();

            Platform.runLater(() -> {
                checkListView = new CheckListView<>();
                checkListView.getItems().add("Item");

                panel.setScene(new Scene(checkListView));

                SwingUtilities.invokeLater(() -> {
                    frame.pack();
                    frame.setVisible(true);
                });
            });

            JButton button = new JButton("Clear list");
            button.addActionListener(event -> Platform.runLater(() -> checkListView.getItems().clear()));

            frame.getContentPane().add(button, BorderLayout.NORTH);
            frame.getContentPane().add(panel);
        });
    }
}
```

**Comment by abhinayagarwal** [comment]
It seems like when you clear the contents of the CheckListView, JavaFX tries to perform a focus cleanup and fails to find the ownercell. The issue is non-existence in a vanilla JavaFX application and surfaces only when we use Swing with JavaFX. Therefore, `CheckListView` seems to performing correctly.

A quick fix can be to assign a focus owner before clearing the items:

```
button.addActionListener(event -> Platform.runLater(() -> {
    checkListView.requestFocus();
    checkListView.getItems().clear();
})); 
```

**Comment by r-smirnov** [comment]
Yes, this issue only affects Swing applications. However, if you replace CheckListView with ListView in the above test case, it works.
