### ISSUE TITLE
Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.controlsfx.control.table.TableRowExpanderColumn.getCellData(int)" is null

### ISSUE THREAD

**Issue by prolancer01** [controlsfx/controlsfx#1365]
When using a table with a TableRowExtenderColumn the following exception happens when the data in the table changes (and/remove/update records) frequently (2 or more chnages per second):

`java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.controlsfx.control.table.TableRowExpanderColumn.getCellData(int)" is null
	at impl.org.controlsfx.skin.ExpandableTableRowSkin.isExpanded(ExpandableTableRowSkin.java:86) ~[controlsfx-11.0.2.jar:?]
	at impl.org.controlsfx.skin.ExpandableTableRowSkin.computePrefHeight(ExpandableTableRowSkin.java:98) ~[controlsfx-11.0.2.jar:?]
	at javafx.scene.control.Control.computePrefHeight(Control.java:570) ~[javafx.controls.jar:?]
	at javafx.scene.Parent.prefHeight(Parent.java:1040) ~[javafx.graphics.jar:?]
	at javafx.scene.layout.Region.prefHeight(Region.java:1559) ~[javafx.graphics.jar:?]
	at javafx.scene.control.skin.VirtualFlow.resizeCell(VirtualFlow.java:1923) ~[javafx.controls.jar:?]
	at javafx.scene.control.skin.VirtualFlow.addTrailingCells(VirtualFlow.java:2125) ~[javafx.controls.jar:?]
	at javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1253) ~[javafx.controls.jar:?]
	at javafx.scene.control.skin.VirtualFlow$5.invalidated(VirtualFlow.java:837) ~[javafx.controls.jar:?]
	at javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:113) ~[javafx.base.jar:?]
	at javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148) ~[javafx.base.jar:?]
	at javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:855) ~[javafx.controls.jar:?]
	at javafx.scene.control.skin.TableViewSkinBase.updateItemCount(TableViewSkinBase.java:554) ~[javafx.controls.jar:?]
	at javafx.scene.control.skin.VirtualContainerBase.checkState(VirtualContainerBase.java:184) ~[javafx.controls.jar:?]
	at javafx.scene.control.skin.VirtualContainerBase.layoutChildren(VirtualContainerBase.java:159) ~[javafx.controls.jar:?]
	at javafx.scene.control.skin.TableViewSkinBase.layoutChildren(TableViewSkinBase.java:406) ~[javafx.controls.jar:?]
	at javafx.scene.control.Control.layoutChildren(Control.java:601) ~[javafx.controls.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1207) ~[javafx.graphics.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1214) ~[javafx.graphics.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1214) ~[javafx.graphics.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1214) ~[javafx.graphics.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1214) ~[javafx.graphics.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1214) ~[javafx.graphics.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1214) ~[javafx.graphics.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1214) ~[javafx.graphics.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1214) ~[javafx.graphics.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1214) ~[javafx.graphics.jar:?]
	at javafx.scene.Scene.doLayoutPass(Scene.java:576) ~[javafx.graphics.jar:?]
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2476) ~[javafx.graphics.jar:?]
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:413) ~[javafx.graphics.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:391) ~[?:?]
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:412) ~[javafx.graphics.jar:?]
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:439) ~[javafx.graphics.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:563) ~[javafx.graphics.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:543) ~[javafx.graphics.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:536) ~[javafx.graphics.jar:?]
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:342) ~[javafx.graphics.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) ~[javafx.graphics.jar:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[javafx.graphics.jar:?]
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) ~[javafx.graphics.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
`

The table is frozen after the exception, however the FX thread appears to continue to work as it is possible to click buttons and scroll ...

The problem is easy to reproduce, just create a table with a TableRowExtenderColumn and run a thread to change (add/remove/update) records randomly at a rate of at least 2 or more a second. We are using ControlsFX 11.0.2, but we will try with the latest 11.1.0 tomorrow. JDK is 15.

**Comment by prolancer01** [comment]
Same issue with ControlsFX 11.1.0 + JDK 16.0.1 + JavaFX 16.
To reproduce, the table need only have 15 or so records in it and the following modify/add/remove operations on the model every second:
1. add 1 new entry
2. modify 3 entries
3. remove 1 entry
The problem should occur within a minute or two.

If you try the same operations but every 2 seconds or so all appears to work fine for an hour (we have not tested longer periods).
