### ISSUE TITLE
CheckComboBox  throw an exception when clicked over the checkbox label

### ISSUE THREAD

**Issue by rolanrbd** [controlsfx/controlsfx#1375]
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: [ fromIndex: 1, toIndex: 2, size: 1 ]
	at impl.org.controlsfx.collections.ReadOnlyUnbackedObservableList.subList(ReadOnlyUnbackedObservableList.java:110)
	at impl.org.controlsfx.collections.ChangeHelper.addRemoveChangeToString(ChangeHelper.java:39)
	at impl.org.controlsfx.collections.MappingChange.toString(MappingChange.java:141)
	at controllers.LttPatternsController$2.onChanged(LttPatternsController.java:117)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at impl.org.controlsfx.collections.ReadOnlyUnbackedObservableList.callObservers(ReadOnlyUnbackedObservableList.java:44)
	at org.controlsfx.control.CheckBitSetModelBase.lambda$new$1(CheckBitSetModelBase.java:125)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at javafx.base/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.base/javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at impl.org.controlsfx.collections.ReadOnlyUnbackedObservableList.callObservers(ReadOnlyUnbackedObservableList.java:44)
	at org.controlsfx.control.CheckBitSetModelBase.check(CheckBitSetModelBase.java:281)
	at org.controlsfx.control.CheckBitSetModelBase.check(CheckBitSetModelBase.java:288)
	at impl.org.controlsfx.skin.CheckComboBoxSkin.lambda$new$1(CheckComboBoxSkin.java:119)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3597)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3899)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1885)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2618)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by abhinayagarwal** [comment]
Can the issue be reproduced with ControlsFX samples? If not, please add a SSCCE to reproduce the behviour.

**Comment by rolanrbd** [comment]
package t002;

import org.controlsfx.control.CheckComboBox;

import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.collections.ListChangeListener;
import javafx.collections.ObservableList;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class TableViewTest extends Application{

	public static void main(String[] args)  {
		// TODO Auto-generated method stub
		launch(args);
	}

	@Override
	public void start(Stage primaryStage) throws Exception {
		// TODO Auto-generated method stub
		try {			
			
			//FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/views/mainView.fxml"));
			VBox root = new VBox(); //fxmlLoader.load();
 
			try {
				CheckComboBox<String> chkCmbFltr = new CheckComboBox<>();
				ObservableList<String> items = FXCollections.observableArrayList();
				items.add("All");
				items.add("1-10");
				items.add("11-19");
				items.add("20-29");
				chkCmbFltr.getItems().setAll(items);
				chkCmbFltr.getItemBooleanProperty(0).set(true);
				
				chkCmbFltr.getCheckModel().getCheckedItems().addListener(new ListChangeListener<Object>() {
					
					@Override				
					public void onChanged(Change c) {
						
						
						while (c.next()) {
							if (c.wasAdded()) {
																
								if (c.toString().contains("All")) {								
									
									// if we call the getCheckModel().clearChecks() this will
									// cause to "remove" the 'All' too at least inside the model.
									// So we need to manually clear everything else
									
									for (int i = chkCmbFltr.getCheckModel().getCheckedIndices().size()-1; i > 0; --i) {									
										int idx = chkCmbFltr.getCheckModel().getCheckedIndices().get(i);										
										if(idx != 0)
											chkCmbFltr.getCheckModel().clearCheck(idx);
									}
								} 
								else {
									// check if the "All" option is selected and if so remove it
									if (chkCmbFltr.getCheckModel().isChecked(0)) {
										chkCmbFltr.getCheckModel().clearCheck(0);
									}
								}
							}
						}	
					}
					
				});
				root.getChildren().add(chkCmbFltr);
			}catch (Exception e) {
				// TODO: handle exception
				e.printStackTrace();
			}
			
			Scene scene = new Scene(root);
			
			primaryStage.setScene(scene);
			primaryStage.setTitle("Hello FXML");
			primaryStage.show();
			
		} catch (Exception e) {
			// TODO: handle exception
		}
	}

}

**Comment by abhinayagarwal** [comment]
This is not a bug in the control. The exception comes from the code written by OP:

```
c.toString().contains("All")
```

needs to be changed by:

```
c.getAddedSubList().contains("All")
```
