### ISSUE TITLE
There is bug in spreadsheetview control

### ISSUE THREAD

**Issue by HamidShaikh1499** [controlsfx/controlsfx#1387]
sorry to say but there is bug. i create one application in that app i used spreadsheetview control and basic idea is that i wrote code to read excel file and set read data to spreadsheetview. that's it. i have one file that file contains 15000 rows but when i set data to spreadsheetview so spreadsheetview controls show errors and after set data it looks like see below image

![Screenshot (26)](https://user-images.githubusercontent.com/50068289/130610703-88a3e9bd-91f5-4b7c-bcec-da03b4796a5d.png)

ERROR : No 3 out of boundexception for length of 3

**i also get this type of error in tableview controls so i have idea about error and i also debugged my code twice time but nothing i found in code !**

**why this happened example row no.998 contains 9 cells but 3 cells contain value and other cell is null so we got above error but apache poi library read that null cell but that not null. I ALSO FACED THIS TYPE OF ERROR IN TABLEVIEW CONTROL**

I resolved that error by below code and i know it is advance version of tableview so may be it will help you i think!

`//Create the table columns, set the cell value factory and add the column to the tableview.
        for (int i = 0; i < excelData.get(0).size(); i++) {
            final int curCol = i;
            final TableColumn<ObservableList<String>, String> column = new TableColumn<>(
                    "Col " + (curCol + 1)
            );
            
            //this below solved my error of this type bug
            column.setText(String.valueOf(i));
            column.setCellValueFactory(
                    param -> {
                        ObservableList<String> values = param.getValue();
                        if(curCol >= values.size())
                            return new ReadOnlyStringWrapper("");
                        else
                            return new ReadOnlyStringWrapper(param.getValue().get(curCol));
                    }
            );
           //above code end

            tableView.getColumns().add(column);
            columnList.add(column);

            column.setCellFactory(TextFieldTableCell.forTableColumn());
            column.setOnEditCommit(event -> {
                int pos = -1;
                List<String> stringList = new ArrayList<>(tableView.getItems().get(0));
                for (String string : stringList) {
                    pos++;
                    if (string.equals(event.getOldValue())) {
                        break;
                    }
                }
                event.getTableView().getItems().get(event.getTablePosition().getRow()).set(pos, event.getNewValue());
            });
        }`

**Comment by HamidShaikh1499** [comment]
sorry for late below is full error regarding this bug

> Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
	at org.controlsfx.control.spreadsheet.SpreadsheetColumn.initCanFix(SpreadsheetColumn.java:405)
	at org.controlsfx.control.spreadsheet.SpreadsheetColumn.<init>(SpreadsheetColumn.java:119)
	at org.controlsfx.control.spreadsheet.SpreadsheetView.setGrid(SpreadsheetView.java:1251)
	at smartseizing.controller.UploadDataController.setExcelSheetToSpreadsheetView(UploadDataController.java:303)
	at smartseizing.controller.UploadDataController.selectFileFromPC(UploadDataController.java:261)
	at smartseizing.controller.UploadDataController.lambda$initView$0(UploadDataController.java:141)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3563)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3865)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1851)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at com.sun.glass.ui.View.notifyMouse(View.java:942)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:832)

**at smartseizing.controller.UploadDataController.setExcelSheetToSpreadsheetView(UploadDataController.java:303) this line show this code from my code lines -> excelSheet.setGrid(excelGrid);**

===============AND======================
below is code where i read and set data to spreadsheetview control



           `try (InputStream inputStream = new FileInputStream(excelFile)) {
            DataFormatter formatter = new DataFormatter();

            Workbook workbook = WorkbookFactory.create(inputStream);
            Sheet sheet = workbook.getSheetAt(0);

            double lastIndexForSheet = Math.min(sheet.getLastRowNum(), 15000);

            int count = 0;
            for (int r=sheet.getFirstRowNum();r<sheet.getLastRowNum();r++) {
                Row row = sheet.getRow(r);
                if(row != null){
                    count = r;
                    ObservableList<SpreadsheetCell> cellObservableList = FXCollections.observableArrayList();
                    for (int i = row.getFirstCellNum(); i <= row.getLastCellNum(); i++) {
                        if (row.getCell(i) != null) {
                            Cell cell = row.getCell(i);
                            if (formatter.formatCellValue(cell) != null) {
                                switch (cell.getCellType()) {
                                    case STRING -> cellObservableList.add(SpreadsheetCellType.STRING.createCell(count, i, 1, 1, cell.getRichStringCellValue().getString()));
                                    case NUMERIC, BOOLEAN -> cellObservableList.add(SpreadsheetCellType.STRING.createCell(count, i, 1, 1, formatter.formatCellValue(cell)));
                                    default -> cellObservableList.add(SpreadsheetCellType.STRING.createCell(count, i, 1, 1, ""));
                                }
                            } else {
                                cellObservableList.add(SpreadsheetCellType.STRING.createCell(count, i, 1, 1, ""));
                            }
                        }
                    }
                    excelSheetCell.add(cellObservableList);
                }

                if (Double.parseDouble(String.valueOf(count)) == lastIndexForSheet-1) {
                    excelGrid = new GridBase(sheet.getLastRowNum(), 26);
                    totalRecordText.setText(String.valueOf(excelSheetCell.size()));
                    fileNameText.setText(excelFile.getName());
                    excelGrid.setRows(excelSheetCell);
                    excelSheet.setGrid(excelGrid);
                }
            }
        } catch (IOException | EncryptedDocumentException ex) {
            System.out.println("MessagesOfError:" + ex);
        }`
