### ISSUE TITLE
NPE while filtering table

### ISSUE THREAD

**Issue by amitjoy** [controlsfx/controlsfx#1417]
```
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.controlsfx.control.table.TableRowExpanderColumn.getCellData(int)" is null
	at impl.org.controlsfx.skin.ExpandableTableRowSkin.isExpanded(ExpandableTableRowSkin.java:86)
	at impl.org.controlsfx.skin.ExpandableTableRowSkin.layoutChildren(ExpandableTableRowSkin.java:107)
	at javafx.controls/javafx.scene.control.Control.layoutChildren(Control.java:601)
	at javafx.controls/javafx.scene.control.Cell.layoutChildren(Cell.java:636)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1207)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.graphics/javafx.scene.Scene.doLayoutPass(Scene.java:579)
	at javafx.graphics/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2515)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:420)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:450)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:575)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:353)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96
```

**Comment by abhinayagarwal** [comment]
Hi Amit,

Can you provide a [SSCCE](http://sscce.org/) to reproduce the issue?

**Comment by amitjoy** [comment]
This is hard to reproduce as it happens unpredictably. I will try to check how I can provide a quick example.

**Comment by amitjoy** [comment]
@abhinayagarwal As I mentioned earlier that it is really hard to reproduce as it happens only when filtering while having one of the rows expanded. But still I didn't manage to see a uniform pattern to reproduce it consistently but it still occurs many times. You could try to look into the stacktrace if something could lead to such a behaviour. 

Thanks in advance.

**Comment by amitjoy** [comment]
Tested Java Runtime - `17.0.2` with `org.controlsfx:controlsfx:11.1.1`

**Comment by amitjoy** [comment]
@abhinayagarwal I just had a quick look into the stacktrace. According to the implementation of `javafx.scene.control.TableColumnBase.getCellData(int)`, it can return `null`. And if it returns `null`, the consumer of it - `impl.org.controlsfx.skin.ExpandableTableRowSkin.isExpanded()` results in NPE. 

I believe it should be fault-tolerant in any case as according to the API, the `javafx.scene.control.TableColumnBase.getCellData(int)` could return `null` anytime.

I think we can introduce something like this:

`Boolean.TRUE.equals(expander.getCellData(getSkinnable().getIndex()))`

This will make it failsafe no matter what `javafx.scene.control.TableColumnBase.getCellData(int)` returns. Could you also kindly have a look?

**Comment by amitjoy** [comment]
You can also use `java.util.Objects.requireNonNullElse(Boolean, Boolean)`

The method would then look as follows:

```
private Boolean isExpanded() {
     return getSkinnable().getItem() != null && Objects.requireNonNullElse(expander.getCellData(getSkinnable().getIndex()), false);
}
```
