### ISSUE TITLE
SpreadsheetView Null Pointer Exceptions

### ISSUE THREAD

**Issue by lad128** [controlsfx/controlsfx#1468]
Greetings,
Trying out SpreadsheetView and the only way it works for me if I call the no argument constructor.
`SpreadsheetView spreadsheetView = new SpreadsheetView();`

When I try something like below, similar to the example in the Javadoc....

public class SpreadsheetViewDemo extends Application {

```
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {

        var a = new SpreadsheetView(getGrid());
        var b = new HBox(a);
        var c = new BorderPane(b);
        var d = new Scene(c);
        primaryStage.setScene(d);
        primaryStage.setTitle("Spread Sheet View Demo");
        primaryStage.show();
    }


    private GridBase getGrid() {
        GridBase gridBase = new GridBase(10, 8);
        ObservableList<ObservableList<SpreadsheetCell>> rows = FXCollections.observableArrayList();

        for (int row = 0; row < gridBase.getRowCount(); ++row) {
            ObservableList<SpreadsheetCell> currentRow = FXCollections.observableArrayList();
            for (int column = 0; column < gridBase.getColumnCount(); ++column) {
                currentRow.add(SpreadsheetCellType.STRING.createCell(row, column, 1, 1, "todo"));
            }
            rows.add(currentRow);
        }
        gridBase.setRows(rows);
        return gridBase;
    }


}
```

I get the following null pointer exceptions
```
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "row" is null
	at impl.org.controlsfx.spreadsheet.GridRowSkin.layoutChildren(GridRowSkin.java:201)
	at javafx.scene.control.Control.layoutChildren(Control.java:588)
	at javafx.scene.control.Cell.layoutChildren(Cell.java:636)
	at javafx.scene.Parent.layout(Parent.java:1207)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Scene.doLayoutPass(Scene.java:580)
	at javafx.scene.Scene.preferredSize(Scene.java:1774)
	at javafx.scene.Scene$2.preferredSize(Scene.java:397)
	at com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.stage.Window$12.invalidated(Window.java:1163)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.stage.Window.setShowing(Window.java:1239)
	at javafx.stage.Window.show(Window.java:1254)
	at javafx.stage.Stage.show(Stage.java:277)
	at com.nestrasoft.nestra.demos.SpreadsheetViewDemo.start(SpreadsheetViewDemo.java:29)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

I searched everywhere but I can't find a resolution.   Does anybody know where I'm going wrong?

**Comment by lad128** [comment]
These are my dependencies and versions

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/20446976/195744103-74fcb704-c621-4652-8201-7e42a799e827.png">

**Comment by fracc9112** [comment]
--module-path %PATH_TO_FX%
--add-modules javafx.swing,javafx.controls,javafx.fxml,javafx.media,javafx.web,javafx.base,javafx.graphics,**org.controlsfx.controls**
--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls
--add-opens=javafx.controls/javafx.scene.control.skin=ALL-UNNAMED
--add-exports=javafx.base/com.sun.javafx.event=org.controlsfx.controls
--add-exports=javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls,
--add-exports=javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls
--add-exports=javafx.graphics/com.sun.javafx.css=org.controlsfx.controls
--add-exports=javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls
--add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls

**Comment by fracc9112** [comment]
[ControlsFX](https://mvnrepository.com/artifact/org.controlsfx/controlsfx) » [11.1.2](https://mvnrepository.com/artifact/org.controlsfx/controlsfx/11.1.2)

**Comment by lad128** [comment]
> 

I've tried using ControlsFx 11.1.2 but it made no difference.  Still getting the same error:
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "row" is null
	at impl.org.controlsfx.spreadsheet.GridRowSkin.layoutChildren(GridRowSkin.java:201)
```

**Comment by fracc9112** [comment]
you have to add those 
(VM arguments)
--module-path %PATH_TO_FX%
--add-modules javafx.swing,javafx.controls,javafx.fxml,javafx.media,javafx.web,javafx.base,javafx.graphics,**org.controlsfx.controls**
--add-opens=javafx.controls/javafx.scene.control.skin=org.controlsfx.controls
--add-opens=javafx.controls/javafx.scene.control.skin=ALL-UNNAMED
--add-exports=javafx.base/com.sun.javafx.event=org.controlsfx.controls
--add-exports=javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls,
--add-exports=javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls
--add-exports=javafx.graphics/com.sun.javafx.css=org.controlsfx.controls
--add-exports=javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls
--add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls

**Comment by lad128** [comment]
> 

I'm not using java modules at the moment.  Do I really need to include the vm arguments?  I tried adding it anyway to try.  I'm using intelij to run the sample class and have added the above vm argument to the run config in Intelij.  Now I get the following error.  I tried adding the javafx swing dependency but same error:
`Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.swing not found

Process finished with exit code 1`

**Comment by lokedhs** [comment]
I'm seeing exactly the same error after upgrading to JavaFX 19. Everything works fine with JavaFX 18. I'm getting the following error when I try to show the component:

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "row" is null
	at impl.org.controlsfx.spreadsheet.GridRowSkin.layoutChildren(GridRowSkin.java:201)
	at javafx.scene.control.Control.layoutChildren(Control.java:588)
	at javafx.scene.control.Cell.layoutChildren(Cell.java:636)
	at javafx.scene.Parent.layout(Parent.java:1207)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Parent.layout(Parent.java:1214)
	at javafx.scene.Scene.doLayoutPass(Scene.java:592)
	at javafx.scene.Scene.preferredSize(Scene.java:1786)
	at javafx.scene.Scene$2.preferredSize(Scene.java:409)
	at com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.stage.Window$12.invalidated(Window.java:1163)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.stage.Window.setShowing(Window.java:1239)
	at javafx.stage.Window.show(Window.java:1254)
	at javafx.stage.Stage.show(Stage.java:277)
	at array.gui.arrayedit.ArrayEditor.show(ArrayEditor.kt:45)
```

I'm using Gradle to build, and I'm already using the same `--add-exports` as was recommended above. I also tried adding the `--add-modules` just to confirm, but that gives me the following error:

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module org.controlsfx.controls not found
```

That said, I don't think that's the issue here. Especially since everything works with the older version of JavaFX.

**Comment by lad128** [comment]
> 

Hi Elias,  thank you for validating what I was experiencing. What you are experiencing is exactly what I found.  I will downgrade to javafx 18 and retest.  There is no particular reason for me to use 19 other than using the latest stable so I have no issue with downgrading to 18 if it works in that version.  Thanks again for responding!

**Comment by lad128** [comment]
> I'm seeing exactly the same error after upgrading to JavaFX 19. Everything works fine with JavaFX 18. I'm getting the following error when I try to show the component:
> 
> ```
> Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "row" is null
> 	at impl.org.controlsfx.spreadsheet.GridRowSkin.layoutChildren(GridRowSkin.java:201)
> 	at javafx.scene.control.Control.layoutChildren(Control.java:588)
> 	at javafx.scene.control.Cell.layoutChildren(Cell.java:636)
> 	at javafx.scene.Parent.layout(Parent.java:1207)
> 	at javafx.scene.Parent.layout(Parent.java:1214)
> 	at javafx.scene.Parent.layout(Parent.java:1214)
> 	at javafx.scene.Parent.layout(Parent.java:1214)
> 	at javafx.scene.Parent.layout(Parent.java:1214)
> 	at javafx.scene.Scene.doLayoutPass(Scene.java:592)
> 	at javafx.scene.Scene.preferredSize(Scene.java:1786)
> 	at javafx.scene.Scene$2.preferredSize(Scene.java:409)
> 	at com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
> 	at javafx.stage.Window$12.invalidated(Window.java:1163)
> 	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
> 	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
> 	at javafx.stage.Window.setShowing(Window.java:1239)
> 	at javafx.stage.Window.show(Window.java:1254)
> 	at javafx.stage.Stage.show(Stage.java:277)
> 	at array.gui.arrayedit.ArrayEditor.show(ArrayEditor.kt:45)
> ```
> 
> I'm using Gradle to build, and I'm already using the same `--add-exports` as was recommended above. I also tried adding the `--add-modules` just to confirm, but that gives me the following error:
> 
> ```
> Error occurred during initialization of boot layer
> java.lang.module.FindException: Module org.controlsfx.controls not found
> ```
> 
> That said, I don't think that's the issue here. Especially since everything works with the older version of JavaFX.
> 
> I did a bit of debugging, and `GridRowSkin.layoutChildren()` is called successfully once per cell (i.e. if the grid contains 4 cells, it gets called properly 4 times). After the calls, there is another call to the same function, but in this case the `row` value is null.

That was exactly the issue -- it appears that controlsfx for SpreadsheetView class has an issue with Javafx 19.  In particular the GridRowSkin class.  I downgraded to Javavx 18 and it works perfectly.
