### ISSUE TITLE
ControlsFXSampler throw error while try to open 'spreadsheet' view 

### ISSUE THREAD

**Issue by icoco** [controlsfx/controlsfx#1492]
java 11 
javafx_version = 17.0.6

run example 'ControlsFXSampler',  failed to open the  'spreadsheet' view, console error message bellow:

`
	Discovering projects...
		Found project 'ControlsFX', with sample base package 'org.controlsfx.samples'
Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class org.controlsfx.control.spreadsheet.GridBase (in module org.controlsfx.controls) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to module org.controlsfx.controls
	at org.controlsfx.controls@11.1.3-SNAPSHOT/org.controlsfx.control.spreadsheet.GridBase.<init>(GridBase.java:183)
`

another issue , many waring message while start the app :

`warning: [module] module not found: org.controlsfx.samples
    exports impl.org.controlsfx.skin to org.controlsfx.samples;
warning: [removal] AccessController in java.security has been deprecated and marked for removal
            String javafxPlatform = AccessController.doPrivileged(new PrivilegedAction<String>() {
                         
....
`

how to solve this issue ?

**Comment by MichaelAntropov** [comment]
Regarding first issue:

> java 11
> javafx_version = 17.0.6
> 
> run example 'ControlsFXSampler', failed to open the 'spreadsheet' view, console error message bellow:
> 
> Discovering projects... Found project 'ControlsFX', with sample base package 'org.controlsfx.samples' Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class org.controlsfx.control.spreadsheet.GridBase (in module org.controlsfx.controls) cannot access class com.sun.javafx.event.EventHandlerManager (in module javafx.base) because module javafx.base does not export com.sun.javafx.event to module org.controlsfx.controls at org.controlsfx.controls@11.1.3-SNAPSHOT/org.controlsfx.control.spreadsheet.GridBase.<init>(GridBase.java:183)

I can see the same error if I try to run `ControlsFXSampler` class directly. But as I understand samples app should be run by using `gradle controlsfx-samples:run`

But I also encountered the same error when I tired to use SpreadsheetView in my application. I use IntellJ IDE so simples solution for me was to add in Run/Debug Configurations a VM options:
```
--add-exports javafx.base/com.sun.javafx.event=org.controlsfx.controls --add-exports javafx.controls/com.sun.javafx.scene.control.behavior=org.controlsfx.controls
```
