### ISSUE TITLE
NPE: Cannot invoke "javafx.geometry.Point2D.getX()" because "this.preDragThumbPoint" is null

### ISSUE THREAD

**Issue by jperedadnr** [controlsfx/controlsfx#1506]
```
java.lang.NullPointerException: Cannot invoke "javafx.geometry.Point2D.getX()" because "this.preDragThumbPoint" is null
    at impl.org.controlsfx.skin.RangeSliderSkin.lambda$initSecondThumb$23(RangeSliderSkin.java:272)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3924)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1890)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2635)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:557)
    at com.sun.glass.ui.View.notifyMouse(View.java:943)
    at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
```
Not easy to reproduce, somehow this could happen if the slider thumb somehow receives a drag event before the pressed event which sets the `preDragThumbPoint`.

**Comment by jperedadnr** [comment]
Somehow this can be reproduced on macOS with a mouse _and_ the touchPad. 

For the sake of the test, I'm adding:

```
public void lowThumbReleased(MouseEvent e) {
        ...
        preDragThumbPoint = null;
    }
```

so I can retry some drag events without needing to restart the application all over again.

Steps:

Running HelloRangeSlider, mouse right-click on the low thumb, drag the thumb, then _while holding the mouse right-click_, press the touchPad, move the thumb and then release the touchPad.

As the mouse is still pressed, the drag event is still on, and preDragThumbPoint is null because there is no new press event.
