### ISSUE TITLE
Bug in HelloGlyphFont.class: Glyph Font page crashes after displaying "ARROW_CIRCLE_O_UP"

### ISSUE THREAD

**Issue by leewyatt** [controlsfx/controlsfx#1548]
#### Description:
There is a bug in the Glyph Font page (HelloGlyphFont.class) of the controlsfx-samples project. Starting from the glyph button "ARROW_CIRCLE_O_UP", subsequent buttons do not display their text or icons correctly. Additionally, switching to another page after this issue occurs results in the other pages appearing blank.

#### Steps to Reproduce:

Launch the controlsfx-samples application.
Navigate to the Glyph Font page.

#### Analysis:
The issue seems to be related to the default setting of MnemonicParsing being true, which prevents underscores from being displayed. LabeledSkinBase internally treats the string length as 14 instead of 17 (due to underscores), causing a string index out of bounds exception when attempting to substring and calculate widths. This appears to be a bug specific to JavaFX 17, as the same functionality works as expected in JavaFX 16 and JavaFX 18.

#### Exception 
```
Exception in thread "JavaFX Application Thread" java.lang.StringIndexOutOfBoundsException: begin 14, end 15, length 14
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at javafx.controls/javafx.scene.control.skin.LabeledSkinBase.layoutLabelInArea(LabeledSkinBase.java:590)
```

![e1](https://github.com/controlsfx/controlsfx/assets/75261429/d7915b96-9cb3-4087-84c3-851c8fc072db)
![e2](https://github.com/controlsfx/controlsfx/assets/75261429/3beea82a-3c7c-4ccd-9bbd-1b6c9ac8491b)
![e3](https://github.com/controlsfx/controlsfx/assets/75261429/170fc28a-ee7a-4351-a26f-9d01cbf91294)

**Comment by abhinayagarwal** [comment]
I ran the sample app with JavaFX 17 with JDK 11 and 17, but unable to reproduce this.

**Comment by leewyatt** [comment]
Hi @abhinayagarwal . Am I running it the wrong way? My system environment and execution method are as follows:

OS: Windows 11  (24H2)

PS D:\Projects\IdeaProjects\controlsfx> java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

PS D:\Projects\IdeaProjects\controlsfx> ./gradlew run        
Starting a Gradle Daemon, 3 busy and 2 incompatible Daemons could not be reused, use --status for details
......
