### ISSUE TITLE
CheckListView.getCheckModel() doesn't select an item if another with a superior index was previously checked

### ISSUE THREAD

**Issue by Rizen59** [controlsfx/controlsfx#1549]
**Description / Steps to reproduce:** 

Run the following code with controlsfx 11.2.1 and click on the button.
As defined in setOnAction(), items 2, 3, 1 should be checked. But only items 2 and 3 are.
If you click again on the button item 1 will be selected.
There is no problem if items are selected in order 1, 2, 3:

**Environment:**

Tested with JDK 21.0.3 / JavaFX 23-ea+20 / controlsfx 11.2.1
No problem with controlsfx 11.1.2, it seems to be a regression from 11.2.0

```java
public class CheckListViewIssue extends Application {

    @Override
    public void start(Stage primaryStage) {
        VBox vbox = new VBox();

        ObservableList<String> items = FXCollections.observableArrayList(
                "Item 1", "Item 2", "Item 3", "Item 4"
        );

        CheckListView<String> checkListView = new CheckListView<>(items);

        Button button = new Button("Select items in this order : 2, 3, 1. Item 1 will not be selected.");
        button.setOnAction(event -> {
            checkListView.getCheckModel().check(items.get(1));
            checkListView.getCheckModel().check(items.get(2));
            checkListView.getCheckModel().check(items.get(0)); // will not be selected
        });

        vbox.getChildren().add(button);
        vbox.getChildren().add(checkListView);

        primaryStage.setScene(new Scene(vbox));
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```

**Comment by thomas-andres** [comment]
I just had an issue with CheckListView as well, which might be the same.

I'm reordering items in a CheckListView and then I restore the selection. In some cases I get an exception:
`java.lang.IndexOutOfBoundsException: [ fromIndex: -1, toIndex: 0, size: 7 ]
	at impl.org.controlsfx.collections.ReadOnlyUnbackedObservableList.subList(ReadOnlyUnbackedObservableList.java:110)
	at javafx.collections.ListChangeListener$Change.getAddedSubList(ListChangeListener.java:243)
	at org.controlsfx.control.CheckBitSetModelBase.lambda$new$2(CheckBitSetModelBase.java:110)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:162)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:71)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:246)
	at impl.org.controlsfx.collections.ReadOnlyUnbackedObservableList.callObservers(ReadOnlyUnbackedObservableList.java:44)
	at org.controlsfx.control.CheckBitSetModelBase.lambda$new$1(CheckBitSetModelBase.java:99)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:162)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:71)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:246)
	at impl.org.controlsfx.collections.ReadOnlyUnbackedObservableList.callObservers(ReadOnlyUnbackedObservableList.java:44)
	at org.controlsfx.control.CheckBitSetModelBase.check(CheckBitSetModelBase.java:259)
	at org.controlsfx.control.CheckBitSetModelBase.check(CheckBitSetModelBase.java:266)
`

I haven't fully figured out the problem, but I think there is something wrong with org.controlsfx.control.CheckBitSetModelBase.BitSetReadOnlyUnbackedObservableList<T>
(I'm using controlsfx 11.2.0 with java fx 22.0.1 and jdk 21)

**Comment by danielpeintner** [comment]
Resolved by https://github.com/controlsfx/controlsfx/pull/1551 ?

**Comment by Rizen59** [comment]
Yes.
I tested this PR and confirm that it resolves the `CheckListViewIssue` example in the first message

**Comment by Rizen59** [comment]
I'm reopening this issue. Although the case in the first comment was resolved, another one still fails:

```java
public class CheckListViewIssue extends Application {

    @Override
    public void start(Stage primaryStage) {
        VBox vbox = new VBox();

        ObservableList<String> items = FXCollections.observableArrayList(
                "Item 1", "Item 2", "Item 3", "Item 4"
        );

        CheckListView<String> checkListView = new CheckListView<>(items);

        Button button = new Button("Check items in this order: 1, 3, 4, 2. Item 2 stays visually unchecked.");
        button.setOnAction(event -> {
            checkListView.getCheckModel().check(items.get(0));
            checkListView.getCheckModel().check(items.get(2));
            checkListView.getCheckModel().check(items.get(3));
            checkListView.getCheckModel().check(items.get(1)); // will not be selected
        });

        vbox.getChildren().add(button);
        vbox.getChildren().add(checkListView);

        primaryStage.setScene(new Scene(vbox));
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```
Tested with JDK 25.0.4 / JavaFX 25.0.4 / controlsfx 11.2.5

**Comment by danielpeintner** [comment]
FYI: There is another pending PR in this area (see https://github.com/controlsfx/controlsfx/pull/1598). Maybe you can check whether it resolves the issue.

**Comment by Rizen59** [comment]
Not entirely — it does fix that last case, but here are 3 new visual and testable cases that are still problematic:

```java
public class CheckListViewIssue extends Application {

    @Override
    public void start(Stage primaryStage) {
        VBox vbox = new VBox();

        ObservableList<String> items = FXCollections.observableArrayList(
                "Item 1", "Item 2", "Item 3", "Item 4", "Item 5"
        );

        CheckListView<String> checkListView = new CheckListView<>(items);

        Button button = new Button("Select items in this order : 1, 2, 2 again, 4. Item 4 will not be selected.");
        button.setOnAction(event -> {
            checkListView.getCheckModel().check(items.get(0));
            checkListView.getCheckModel().check(items.get(1));
            checkListView.getCheckModel().check(items.get(1)); // already checked, no-op on the model
            checkListView.getCheckModel().check(items.get(3)); // checked in the model, rendered unchecked
        });

        vbox.getChildren().add(button);
        vbox.getChildren().add(checkListView);

        primaryStage.setTitle("CheckListViewIssue3");
        primaryStage.setScene(new Scene(vbox));
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```
```java
public class CheckListViewIssue extends Application {

    @Override
    public void start(Stage primaryStage) {
        VBox vbox = new VBox();

        ObservableList<String> items = FXCollections.observableArrayList(
                "Item 1", "Item 2", "Item 3", "Item 4", "Item 5"
        );

        CheckListView<String> checkListView = new CheckListView<>(items);

        Button button = new Button("Select items 1, 4, 5 then select item 2 with checkIndices. Item 2 will not be selected.");
        button.setOnAction(event -> {
            checkListView.getCheckModel().check(items.get(0));
            checkListView.getCheckModel().check(items.get(3));
            checkListView.getCheckModel().check(items.get(4));
            checkListView.getCheckModel().checkIndices(1); // checked in the model, rendered unchecked
        });

        vbox.getChildren().add(button);
        vbox.getChildren().add(checkListView);

        primaryStage.setTitle("CheckListViewIssue4");
        primaryStage.setScene(new Scene(vbox));
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```
```java
public class CheckListViewIssue extends Application {

    @Override
    public void start(Stage primaryStage) {
        VBox vbox = new VBox();

        ObservableList<String> items = FXCollections.observableArrayList(
                "Item 1", "Item 2", "Item 3", "Item 4", "Item 5"
        );

        CheckListView<String> checkListView = new CheckListView<>(items);

        Button button = new Button("Select items 1, 4, 5, unselect item 2 which is not selected, then select item 3. Item 3 will not be selected.");
        button.setOnAction(event -> {
            checkListView.getCheckModel().check(items.get(0));
            checkListView.getCheckModel().check(items.get(3));
            checkListView.getCheckModel().check(items.get(4));
            checkListView.getCheckModel().clearCheck(items.get(1)); // not checked, no-op on the model
            checkListView.getCheckModel().check(items.get(2)); // checked in the model, rendered unchecked
        });

        vbox.getChildren().add(button);
        vbox.getChildren().add(checkListView);

        primaryStage.setTitle("CheckListViewIssue5");
        primaryStage.setScene(new Scene(vbox));
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
```
I'll open a PR that handles all 5 cases (cases 1 and 3 already work on master, case 2 is fixed by https://github.com/controlsfx/controlsfx/pull/1598, but case 3 no longer works with it).
