### ISSUE TITLE
SearchableComboBox

### ISSUE THREAD

**Issue by JonathanGiles** [controlsfx/controlsfx#930]
**[Original report](https://bitbucket.org/controlsfx/controlsfx/issue/739) by Tobias Schulte (Bitbucket: [tobias_schulte](https://bitbucket.org/tobias_schulte), GitHub: Unknown).**

----------------------------------------

I have created a Searchable ComboBox. It functions a bit like the combo boxes for Component and Milestone in the bitbucket "Create issue" page.

If you are interested, I would like to offer creating a pull request.

**Comment by showbags** [comment]
I'm just trying this control for the first time and it *almost* does exactly what I need. I can see from the initial proposal that the control "Currently the Control only works with editable=false". From a UI perspective it seems that it should be able to work with editable=true. I'm not really up to speed with skins and editors but would it be relatively easy to make it work in editable mode?

**Comment by Auriga2** [comment]
This is a really nice control but I got a weird issue when I tried to change the drop down list dynamically in the code, triggered by another user selection. When the drop down changed from a longer list to a shorter list, the below exception is thrown, at either of these lines:
```
searchableComboBox.getSelectionModel().clearSelection();
searchableComboBox.setItems(FXCollections.observableList(options));
```
Exception:
`java.util.NoSuchElementException
	at java.base/java.util.AbstractList$Itr.next(AbstractList.java:377)
	at java.base/java.util.AbstractList.indexOf(AbstractList.java:188)
	at javafx.controls/javafx.scene.control.skin.ComboBoxListViewSkin.getIndexOfComboBoxValueInItemsList(ComboBoxListViewSkin.java:467)
	at javafx.controls/javafx.scene.control.skin.ComboBoxListViewSkin.updateDisplayNode(ComboBoxListViewSkin.java:349)
	at javafx.controls/javafx.scene.control.skin.ComboBoxListViewSkin.getDisplayNode(ComboBoxListViewSkin.java:266)
	at javafx.controls/javafx.scene.control.skin.ComboBoxBaseSkin.updateDisplayArea(ComboBoxBaseSkin.java:289)
	at javafx.controls/javafx.scene.control.skin.ComboBoxBaseSkin.lambda$new$7(ComboBoxBaseSkin.java:133)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at javafx.controls/com.sun.javafx.scene.control.LambdaMultiplePropertyChangeListenerHandler.lambda$new$1(LambdaMultiplePropertyChangeListenerHandler.java:49)
	at javafx.base/javafx.beans.value.WeakChangeListener.changed(WeakChangeListener.java:86)
[catch] at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at javafx.base/javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:72)
	at javafx.base/com.sun.javafx.binding.BidirectionalBinding$TypedGenericBidirectionalBinding.changed(BidirectionalBinding.java:601)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:360)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:106)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at javafx.controls/javafx.scene.control.ComboBoxBase.setValue(ComboBoxBase.java:151)
	at javafx.controls/javafx.scene.control.ComboBox.updateValue(ComboBox.java:520)
	at javafx.controls/javafx.scene.control.ComboBox.access$200(ComboBox.java:194)
	at javafx.controls/javafx.scene.control.ComboBox$3.changed(ComboBox.java:503)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.base/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at javafx.controls/javafx.scene.control.SelectionModel.setSelectedItem(SelectionModel.java:105)
	at javafx.controls/javafx.scene.control.ComboBox$ComboBoxSelectionModel.lambda$new$0(ComboBox.java:560)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
	at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.base/javafx.beans.property.ReadOnlyIntegerPropertyBase.fireValueChangedEvent(ReadOnlyIntegerPropertyBase.java:72)
	at javafx.base/javafx.beans.property.ReadOnlyIntegerWrapper.fireValueChangedEvent(ReadOnlyIntegerWrapper.java:102)
	at javafx.base/javafx.beans.property.IntegerPropertyBase.markInvalid(IntegerPropertyBase.java:114)
	at javafx.base/javafx.beans.property.IntegerPropertyBase.set(IntegerPropertyBase.java:148)
	at javafx.controls/javafx.scene.control.SelectionModel.setSelectedIndex(SelectionModel.java:69)
	at javafx.controls/javafx.scene.control.SingleSelectionModel.updateSelectedIndex(SingleSelectionModel.java:215)
	at javafx.controls/javafx.scene.control.SingleSelectionModel.clearSelection(SingleSelectionModel.java:68)`

I couldn't find the exact issue, but appreciate if someone can shed some light.

**Comment by danielpeintner** [comment]
relates to https://github.com/controlsfx/controlsfx/issues/1320

**Comment by abhinayagarwal** [comment]
@danielpeintner Since SearchableComboBox is already integrated in the library, should we close this issue?

**Comment by danielpeintner** [comment]
My opinion is as follows.
* we need to acknowledge that  there is a problem with  `SearchableComboBox` if the list dynamically changes. So either this issue or #1320 should be kept open to track that.
* I would rather suggest to re-open #1320 (which was closed by the initial reporter) since this issue was mainly about integrating `SearchableComboBox` in the first place (which happened as you pointed out already)
