### ISSUE TITLE
IllegalAccessError: class impl.org.controlsfx.version.VersionChecker (in unnamed module) cannot access class com.sun.javafx.runtime.VersionInfo (in module javafx.base) because module javafx.base does not export com.sun.javafx.runtime to unnamed module

### ISSUE THREAD

**Issue by JonathanGiles** [controlsfx/controlsfx#974]
**[Original report](https://bitbucket.org/controlsfx/controlsfx/issue/783) by Fouad Almalki (Bitbucket: [eng-fouad](https://bitbucket.org/eng-fouad), GitHub: [eng-fouad](https://github.com/eng-fouad)).**

----------------------------------------

The following exception occurs when using NotificationPane through Webstart (works fine in normal environment):

```
Exception in thread "JavaFX Application Thread" java.lang.IllegalAccessError: class impl.org.controlsfx.version.VersionChecker (in unnamed module @0x79b4759) cannot access class com.sun.javafx.runtime.VersionInfo (in module javafx.base) because module javafx.base does not export com.sun.javafx.runtime to unnamed module @0x79b4759
	at impl.org.controlsfx.version.VersionChecker.<clinit>(VersionChecker.java:50)
	at org.controlsfx.control.ControlsFXControl.<init>(ControlsFXControl.java:35)
	at org.controlsfx.control.NotificationPane.<init>(NotificationPane.java:208)
	at org.controlsfx.control.NotificationPane.<init>(NotificationPane.java:194)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.lang.Class.newInstance(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader$ValueElement.processStartElement(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.processStartElement(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at javafx.fxml/javafx.fxml.FXMLLoader.load(Unknown Source)
	/* unrelated lines removed */
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by phinney** [comment]
I got the same exception tying to get the javafx version info using the call VersionInfo.getRuntimeVersion().toString().  The workaround for me was to use System.getProperty("javafx.runtime.version")
